package com.sap.document.sap.soap.functions.mc_style;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.blazer.util.PathUtil;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-07-25T14:45:01.592+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "service", 
                  wsdlLocation = "file:/Users/hyy/wsdl/wsdl_20170725.xml",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "service");
    public final static QName Binding = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding");
    public final static QName BindingSOAP12 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12");
    static {
        URL url = null;
        try {
//            url = new URL("file:/Users/hyy/wsdl/wsdl_20170725_2.xml");
			url = new File(PathUtil.resource + "document20170725.xml").toURI().toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/hyy/wsdl/wsdl_20170725.xml");
        }
        WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZHRJFPERINTERFACE
     */
    @WebEndpoint(name = "binding")
    public ZHRJFPERINTERFACE getBinding() {
        return super.getPort(Binding, ZHRJFPERINTERFACE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZHRJFPERINTERFACE
     */
    @WebEndpoint(name = "binding")
    public ZHRJFPERINTERFACE getBinding(WebServiceFeature... features) {
        return super.getPort(Binding, ZHRJFPERINTERFACE.class, features);
    }


    /**
     *
     * @return
     *     returns ZHRJFPERINTERFACE
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZHRJFPERINTERFACE getBindingSOAP12() {
        return super.getPort(BindingSOAP12, ZHRJFPERINTERFACE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZHRJFPERINTERFACE
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZHRJFPERINTERFACE getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(BindingSOAP12, ZHRJFPERINTERFACE.class, features);
    }

}
