
package com.sap.document.sap.soap.functions.mc_style;

import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Holder;

import org.blazer.util.PathUtil;

/**
 * This class was generated by Apache CXF 3.1.6 2017-03-23T16:10:37.698+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class ZHRJFPERINTERFACE_Binding_Client {

	private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "service");

	private ZHRJFPERINTERFACE_Binding_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		String imDate = "2017-05-17";
		String imDays = "00";
		if (args.length >= 1) {
			imDate = args[0];
		}
		if (args.length >= 2) {
			imDays = args[1];
		}
		try {
			URL wsdlURL = Service.WSDL_LOCATION;
			Service ss = new Service(wsdlURL, SERVICE_NAME);
			ZHRJFPERINTERFACE port = ss.getBinding();
			TableOfZshrJfpernr jfpernr = new TableOfZshrJfpernr();
			Holder<TableOfZshrJfpernr> rst = new Holder<TableOfZshrJfpernr>(jfpernr);
			{
				long l1 = System.currentTimeMillis();
				TableOfZhrsHtPernr htPernr = new TableOfZhrsHtPernr();
				Holder<TableOfZhrsHtPernr> holder = new Holder<TableOfZhrsHtPernr>(htPernr);
				port.zdefmHrJfper(rst, imDate, imDays, holder);
				long l2 = System.currentTimeMillis();
				System.out.println("取数消耗时间：" + (l2 - l1));
			}
			String outPath = PathUtil.root + imDate + "-" + imDays + ".csv";
			OutputStreamWriter out = new OutputStreamWriter(new FileOutputStream(outPath), "UTF-8");
			for (ZshrJfpernr t : rst.value.item) {
				String outString = t.showData();
				if (outString != null && !"".equals(outString)) {
					// 过滤文字中间出现换行符
					outString = outString.replaceAll("\r\n", "").replaceAll("\n", "").replaceAll("\r", "");
				}
				out.write(outString + "\n");
			}
			System.out.println("获取数据[" + rst.value.item.size() + "]条");
			out.flush();
			out.close();
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

}
